# Generated by Django 5.2.4 on 2025-08-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politico',
            name='foto',
            field=models.ImageField(blank=True, help_text='Upload da foto (opcional)', null=True, upload_to='politicos/'),
        ),
        migrations.AlterField(
            model_name='politico',
            name='foto_url',
            field=models.URLField(blank=True, help_text='URL da foto (opcional)', null=True),
        ),
    ]
